#!/usr/bin/env node
// Regenerates docs/tasks/index.md from docs/tasks/*.md frontmatter.
// Zero dependencies.
//
// Standalone usage:
//   node build-index.mjs [tasks-dir]
//
// Programmatic usage:
//   import { buildIndex } from './build-index.mjs';
//   await buildIndex('docs/tasks');

import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { progressBar, parseYamlScalar } from './lib.mjs';

export async function buildIndex(tasksDir = 'docs/tasks') {
  const INDEX_FILE = join(tasksDir, 'index.md');

  let files;
  try {
    files = await readdir(tasksDir);
  } catch (err) {
    if (err.code === 'ENOENT') {
      await mkdir(tasksDir, { recursive: true });
      files = [];
    } else {
      throw err;
    }
  }

  files = files.filter((f) => f.endsWith('.md') && f !== 'index.md' && !f.startsWith('_'));

  const tasks = [];
  for (const f of files) {
    const raw = await readFile(join(tasksDir, f), 'utf8');
    const fm = parseFrontmatter(raw);
    if (!fm || !fm.id) continue;
    tasks.push({ file: f, ...fm, debts: countOpenDebts(raw) });
  }

  const active = tasks.filter((t) => !['done', 'blocked'].includes(t.phase));
  const blocked = tasks.filter((t) => t.phase === 'blocked');
  const done = tasks
    .filter((t) => t.phase === 'done')
    .sort((a, b) => (b.updated || '').localeCompare(a.updated || ''))
    .slice(0, 10);

  const out = [
    '<!-- AUTO-GENERATED by run-task-pipeline skill. Do not edit manually. -->',
    `<!-- Last updated: ${new Date().toISOString()} -->`,
    '',
    '# Tasks',
    '',
    '## Active',
    '',
    renderActive(active),
    '',
    '## Blocked',
    '',
    renderBlocked(blocked),
    '',
    '## Done (last 10)',
    '',
    renderDone(done),
    '',
  ].join('\n');

  await writeFile(INDEX_FILE, out);
  return {
    indexFile: INDEX_FILE,
    active: active.length,
    blocked: blocked.length,
    done: done.length,
  };
}

// Counts open `- [ ]` checkboxes in the body (after frontmatter).
// Leading whitespace + flexible spacing, the same shape debt-report
// aggregators match, so the index numbers agree with them.
// Caveat: matches inside fenced code blocks too — accepted as approximation,
// the usual blind spot of line-based debt aggregators.
function countOpenDebts(raw) {
  const body = raw.replace(/^---\n[\s\S]*?\n---\n?/, '');
  const m = body.match(/^\s*-\s*\[ \]\s+/gm);
  return m ? m.length : 0;
}

function parseFrontmatter(raw) {
  const m = raw.match(/^---\n([\s\S]*?)\n---/);
  if (!m) return null;
  const obj = {};
  for (const line of m[1].split('\n')) {
    // Only top-level keys (no leading whitespace). Nested objects are skipped.
    const kv = line.match(/^([a-zA-Z_][\w-]*):\s*(.*)$/);
    if (!kv) continue;
    // Shared unquoting: titles are written with JSON.stringify, so a plain
    // quote-strip leaves \" visible in the generated index.
    obj[kv[1]] = parseYamlScalar(kv[2].trim());
  }
  return obj;
}

function row(cells) {
  return '| ' + cells.map((c) => (c == null || c === '' ? '—' : String(c))).join(' | ') + ' |';
}

function renderActive(tasks) {
  if (!tasks.length) return '_No active tasks._';
  const sorted = tasks.sort((a, b) => (b.updated || '').localeCompare(a.updated || ''));
  return [
    '| ID | Title | Type | Pipeline | Phase | Progress | Updated | Debt |',
    '| --- | --- | --- | --- | --- | --- | --- | --- |',
    ...sorted.map((t) =>
      row([
        `[${t.id}](./${t.file})`,
        t.title,
        t.type,
        t.pipeline,
        t.phase,
        renderProgress(t),
        t.updated,
        t.debts > 0 ? t.debts : null,
      ]),
    ),
  ].join('\n');
}

function renderProgress(t) {
  const total = Number(t.steps_total) || 0;
  if (!total) return null;
  const done = Number(t.steps_done) || 0;
  return `${progressBar(done, total)} ${done}/${total}`;
}

function renderBlocked(tasks) {
  if (!tasks.length) return '_No blocked tasks._';
  return [
    '| ID | Title | Blocked by | Updated |',
    '| --- | --- | --- | --- |',
    ...tasks.map((t) =>
      row([`[${t.id}](./${t.file})`, t.title, t.blocked_by, t.updated]),
    ),
  ].join('\n');
}

function renderDone(tasks) {
  if (!tasks.length) return '_No completed tasks yet._';
  return [
    '| ID | Title | Finished |',
    '| --- | --- | --- |',
    ...tasks.map((t) => row([`[${t.id}](./${t.file})`, t.title, t.updated])),
  ].join('\n');
}

// Standalone CLI entry — only when invoked directly, not on import.
const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const dir = process.argv[2] || 'docs/tasks';
  buildIndex(dir)
    .then((r) => {
      console.log(
        `Wrote ${r.indexFile} — active: ${r.active}, blocked: ${r.blocked}, done(shown): ${r.done}`,
      );
    })
    .catch((err) => {
      console.error(err);
      process.exit(1);
    });
}
