import Foundation

/// The most frequent words of 1–3 letters per language, generated by `ModelTrainer`
/// from the training corpora (`ShortWordTable+Generated.swift`).
///
/// Short words carry too few characters for the n-gram model to decide on its own
/// ("ns" → "ты"), so the detector uses this fixed set instead: a short word that is
/// common in the language it was typed in is kept, and a short word whose conversion
/// is common in the other language is a correction candidate.
public enum ShortWordTable {
    public static let maxLength = 3

    public static func contains(_ word: String, language: ModelLanguage) -> Bool {
        generated[language]?.contains(TextNormalization.normalize(word)) ?? false
    }

    public static func words(for language: ModelLanguage) -> Set<String> {
        generated[language] ?? []
    }
}
